"""The invariant that makes this repository safe to publish.

Reports generated by this suite are committed to a public repository.  They
must never carry host identifiers: no hostname, no IP address, no EC2
instance ID, no availability zone.  neuron-monitor volunteers several of
these in every sample, so the guard has to be active, not aspirational.

If you are here because this test failed, do not relax it -- find what
started emitting the identifier and stop it at the source.
"""

import glob
import json
import os
import pathlib
import re
import socket

import pytest

import neuron_device
import neuron_monitor
import pantheon_neuron


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FORBIDDEN_KEYS = (
    "instance_info",
    "instance_id",
    "instance_type",
    "availability_zone",
    "region",
    "ami_id",
    "subnet_id",
    "hostname",
    "ip_address",
    "mac_address",
    "network_info",
)


def _flatten(value, out=None):
    """Collect every key and scalar in a nested structure."""
    out = [] if out is None else out
    if isinstance(value, dict):
        for key, item in value.items():
            out.append(str(key))
            _flatten(item, out)
    elif isinstance(value, list):
        for item in value:
            _flatten(item, out)
    else:
        out.append(str(value))
    return out


@pytest.fixture
def mock_env(monkeypatch):
    monkeypatch.setenv("PANTHEON_NEURON_MOCK", "1")
    yield
    monkeypatch.delenv("PANTHEON_NEURON_MOCK", raising=False)


def test_snapshot_contains_no_host_identifier_keys(mock_env):
    snapshot = pantheon_neuron.get_system_snapshot(neuron_device.discover())
    tokens = {token.lower() for token in _flatten(snapshot)}
    for key in FORBIDDEN_KEYS:
        assert key not in tokens, f"snapshot leaked '{key}'"


def test_snapshot_does_not_contain_this_machines_hostname(mock_env):
    """A key-name blocklist is not enough; check the actual value."""
    snapshot = pantheon_neuron.get_system_snapshot(neuron_device.discover())
    blob = json.dumps(snapshot).lower()

    hostname = socket.gethostname().lower()
    assert hostname
    assert hostname not in blob, "snapshot leaked the running host's name"

    fqdn = socket.getfqdn().lower()
    if fqdn and fqdn != "localhost":
        assert fqdn not in blob, "snapshot leaked the running host's FQDN"


def test_monitor_scrubs_instance_info_from_samples():
    """neuron-monitor emits instance_info; it must not survive ingest."""
    raw = {
        "instance_info": {
            "instance_id": "i-0123456789abcdef0",
            "instance_type": "trn1.32xlarge",
            "availability_zone": "us-east-1d",
        },
        "neuron_runtime_data": [
            {"report": {"execution_stats": {"total_executions": 5}}}
        ],
    }
    scrubbed = neuron_monitor._scrub(raw)

    assert "instance_info" not in scrubbed
    assert "i-0123456789abcdef0" not in json.dumps(scrubbed)
    # ...without discarding the metrics we actually came for.
    assert scrubbed["neuron_runtime_data"][0]["report"]["execution_stats"] == {
        "total_executions": 5
    }


def test_monitor_scrubs_nested_identifiers():
    raw = {"outer": {"inner": [{"hostname": "ip-10-0-0-1", "value": 3}]}}
    scrubbed = neuron_monitor._scrub(raw)
    assert "ip-10-0-0-1" not in json.dumps(scrubbed)
    assert scrubbed["outer"]["inner"][0]["value"] == 3


def test_aggregated_telemetry_is_clean(mock_env):
    """The mock loop deliberately injects instance_info to prove the path."""
    monitor = neuron_monitor.NeuronMonitor(period_seconds=0.01, mock=True)
    monitor.start([0, 1])
    import time

    time.sleep(0.1)
    metrics = monitor.stop()

    blob = json.dumps(metrics).lower()
    for key in FORBIDDEN_KEYS:
        assert key not in blob, f"aggregated telemetry leaked '{key}'"


def _named(name):
    from kernels import registry
    return next(w for w in registry.WORKLOADS if w.name == name)


def _report_is_clean(report, label):
    tokens = {token.lower() for token in _flatten(report)}
    for key in FORBIDDEN_KEYS:
        assert key not in tokens, f"{label} leaked '{key}'"


def test_a_freshly_written_report_is_clean(mock_env, tmp_path, monkeypatch):
    """The check that actually runs in CI.

    Its predecessor parametrised over ``database/*.json`` -- and
    ``database/`` is in .gitignore, so a fresh checkout has none and
    pytest reported "got empty parameter set" and skipped. **The privacy
    guard has been vacuous in CI since it was written**, in the one job
    that was deliberately split out of the matrix so a single green check
    could not hide it.

    It was found by deleting some local reports and noticing the skip
    count go up by one.

    So this generates a report instead of hoping to find one. A run whose
    reports are written by the code under test is the only version of
    this check that can fail on a machine that has never run a workload.
    """
    monkeypatch.setattr(pantheon_neuron, "DATABASE_DIR", str(tmp_path))
    devices = [neuron_device.NeuronDevice(0, "trn1", "v2", 2, 32 * 1024**3, True)]
    rows = [pantheon_neuron.run_workload(
        _named("memory_read"), devices, 0.02, 0.01)]
    snapshot = pantheon_neuron.get_system_snapshot(devices)
    path = pantheon_neuron.write_report(snapshot, rows, "privacy-check")

    written = sorted(tmp_path.glob("*.json"))
    assert written, "the run wrote no report, so nothing was checked"

    with open(path, encoding="utf-8") as handle:
        _report_is_clean(json.load(handle), os.path.basename(path))


@pytest.mark.parametrize(
    "path", sorted(glob.glob(os.path.join(REPO_ROOT, "database", "*.json")))
)
def test_any_local_report_is_also_clean(path):
    """Kept for the developer case: reports from real runs sit in
    database/ on a machine that has run the suite, and those are the ones
    most likely to carry a host identifier.

    This one legitimately has nothing to do on a fresh checkout. The test
    above is what covers CI, so an empty parameter set here is no longer
    a silent gap.
    """
    with open(path, encoding="utf-8") as handle:
        _report_is_clean(json.load(handle), os.path.basename(path))


# --- committed probe data ---------------------------------------------------

_IDENTIFIER_PATTERNS = (
    (r"\bi-[0-9a-f]{8,17}\b", "EC2 instance id"),
    (r"\bami-[0-9a-f]{8,17}\b", "AMI id"),
    (r"\bsubnet-[0-9a-f]{8,17}\b", "subnet id"),
    (r"\bsg-[0-9a-f]{8,17}\b", "security group id"),
    (r"\bvpc-[0-9a-f]{8,17}\b", "VPC id"),
    (r"\b(?:us|eu|ap|sa|ca|me|af)-[a-z]+-\d[a-f]\b", "availability zone"),
    # A bare 12-digit number is not an account id -- effective_flops
    # readings are 12 digits. Require account context.
    (r"arn:aws[^\s]*:\d{12}:", "AWS account id in an ARN"),
    (r"(?i)account[^\n]{0,24}?\b\d{12}\b", "AWS account id"),
)


def _committed_text_files():
    """Every text file tracked in the repo's data and docs directories."""
    found = []
    for directory in ("data", "docs"):
        root = os.path.join(REPO_ROOT, directory)
        for base, _, names in os.walk(root):
            for name in names:
                if name.endswith((".md", ".txt", ".json")):
                    found.append(os.path.join(base, name))
    return sorted(found)


@pytest.mark.parametrize("path", _committed_text_files())
def test_committed_data_carries_no_identifiers(path):
    """Probe captures are committed to a public repo; they must be redacted.

    Raw neuron-monitor and neuron-ls output is thick with instance ids, AMI
    ids, subnet ids and availability zones. Redaction is done by hand when
    the capture is transcribed, so it needs a machine check behind it.
    """
    with open(path, encoding="utf-8") as handle:
        text = handle.read()

    for pattern, label in _IDENTIFIER_PATTERNS:
        match = re.search(pattern, text)
        assert match is None, (
            f"{os.path.relpath(path, REPO_ROOT)} contains a real {label}: "
            f"{match.group(0)!r} — redact it"
        )


def test_the_measurement_field_carries_no_paths(monkeypatch):
    """Provenance is a whitelist, and it must never widen into a path.

    `profiler_neff` is a basename on purpose: the compiler's own workdirs
    are under /tmp/no-user/... and a caller-set PANTHEON_NEURON_WORKDIR can
    sit anywhere, including a home directory. A path in a published row
    leaks a username.
    """
    for key in pantheon_neuron._PROVENANCE_KEYS:
        assert not key.endswith("_path"), key
        assert "workdir" not in key, key
        assert "session" not in key, key


def test_provenance_is_a_whitelist_not_a_dump():
    """A kernel result also holds plan dicts and paths that must not publish."""
    workload = next(w for w in pantheon_neuron.registry.WORKLOADS
                    if w.name == "memory_read")
    pantheon_neuron._LAST_RUN[workload.name] = {
        "profiler_gbps": 256.17,
        "profiler_neff": "model.neff",
        "profiler_candidates_tried": 1,
        "hbm_read_bytes": 1073741824,
        # None of the below may reach a report row.
        "session_path": "/home/someone/pantheon_ccwork/memory_read.ntff",
        "workdir": "/home/someone/pantheon_ccwork",
        "plan": {"tiles": 8192},
    }
    try:
        found = pantheon_neuron._provenance(workload)
    finally:
        pantheon_neuron._LAST_RUN.pop(workload.name, None)

    assert found["profiler_neff"] == "model.neff"
    assert found["profiler_candidates_tried"] == 1
    assert "session_path" not in found
    assert "workdir" not in found
    assert "plan" not in found
    assert "someone" not in json.dumps(found)


def test_provenance_is_absent_rather_than_empty():
    """A workload that recorded nothing gets None, not a misleading {}."""
    workload = next(w for w in pantheon_neuron.registry.WORKLOADS
                    if w.name == "baseline_metrics")
    pantheon_neuron._LAST_RUN.pop(workload.name, None)
    assert pantheon_neuron._provenance(workload) is None


def test_the_provenance_whitelist_has_no_duplicates():
    """It listed implied_tflops twice.

    Harmless -- it is used as a membership test -- and still worth a
    check: a whitelist nobody reads is a whitelist that drifts, and the
    duplicate was the visible symptom of nobody reading it.
    """
    keys = pantheon_neuron._PROVENANCE_KEYS
    duplicates = sorted({k for k in keys if list(keys).count(k) > 1})
    assert not duplicates, duplicates


def test_every_whitelisted_key_is_something_a_kernel_reports():
    """A key no kernel produces is dead whitelist entry, and the list is
    the only thing standing between a report and a leaked path.

    Read through the comment filter so a key mentioned only in prose does
    not count -- the same way two dead verify_ functions hid behind
    docstrings that credited them.
    """
    import sourcecheck

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    code = ""
    for name in sorted(os.listdir(os.path.join(root, "kernels"))):
        if name.endswith(".py"):
            with open(os.path.join(root, "kernels", name),
                      encoding="utf-8") as handle:
                code += sourcecheck.code_only(handle.read())
    with open(os.path.join(root, "pantheon_neuron.py"),
              encoding="utf-8") as handle:
        orchestrator = sourcecheck.code_only(handle.read())

    assert code, "no kernel source read -- the sweep is broken"

    orphans = [key for key in pantheon_neuron._PROVENANCE_KEYS
               if f'"{key}"' not in code
               and f'"{key}"' not in orchestrator.replace(
                   "_PROVENANCE_KEYS", "")]
    assert not orphans, orphans


# -- the JSON that is not JSON ----------------------------------------------

def test_a_non_finite_value_does_not_reach_the_file(tmp_path, monkeypatch):
    """NaN and Infinity are not JSON. Python emits the bare tokens by
    default and reads them back, so a report can look fine here and fail in
    every consumer that is not Python."""
    monkeypatch.setattr(pantheon_neuron, "DATABASE_DIR", str(tmp_path))
    rows = [{"Test Name": "x", "Score": float("nan"),
             "Telemetry": {"power": [1.0, float("inf")]}}]
    path = pantheon_neuron.write_report({"devices": []}, rows, "runid")

    raw = pathlib.Path(path).read_text(encoding="utf-8")
    assert "NaN" not in raw and "Infinity" not in raw
    # Strict: json.loads accepts the tokens unless asked not to.
    payload = json.loads(raw, parse_constant=_reject)
    assert payload["test_results"][0]["Score"] is None
    assert payload["test_results"][0]["Telemetry"]["power"] == [1.0, None]
    assert payload["non_finite_fields"] == [
        "test_results[0].Score", "test_results[0].Telemetry.power[1]"]


def _reject(token):
    raise AssertionError(f"the report carried {token}")


def test_a_finite_report_records_no_dropped_fields(tmp_path, monkeypatch):
    monkeypatch.setattr(pantheon_neuron, "DATABASE_DIR", str(tmp_path))
    path = pantheon_neuron.write_report({"devices": []},
                                        [{"Test Name": "x", "Score": 1.5}], "runid")
    payload = json.loads(pathlib.Path(path).read_text(encoding="utf-8"))
    assert "non_finite_fields" not in payload


def test_a_non_finite_score_fails_the_row(mock_env, monkeypatch):
    """Every comparison against NaN answers False, so the ceiling check and
    the disagreement check both pass it through."""
    from kernels import registry
    from neuron_device import NeuronDevice

    monkeypatch.setattr(pantheon_neuron, "_execute", lambda *a: float("nan"))
    workload = next(w for w in registry.WORKLOADS if w.name == "tensor_virus")
    devices = [NeuronDevice(0, "trn1", "v2", 2, 32 * 1024**3, True)]
    row = pantheon_neuron.run_workload(
        workload, devices, duration=0.02, monitor_period=0.01)
    assert row["Status"] == "FAIL"
    assert row["Score"] is None
    assert "not a finite number" in row["Detail"]
