"""The invariant that makes this repository safe to publish.

Reports generated by this suite are committed to a public repository.  They
must never carry host identifiers: no hostname, no IP address, no EC2
instance ID, no availability zone.  neuron-monitor volunteers several of
these in every sample, so the guard has to be active, not aspirational.

If you are here because this test failed, do not relax it -- find what
started emitting the identifier and stop it at the source.
"""

import glob
import json
import os
import socket

import pytest

import neuron_device
import neuron_monitor
import pantheon_neuron


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FORBIDDEN_KEYS = (
    "instance_info",
    "instance_id",
    "instance_type",
    "availability_zone",
    "region",
    "ami_id",
    "subnet_id",
    "hostname",
    "ip_address",
    "mac_address",
    "network_info",
)


def _flatten(value, out=None):
    """Collect every key and scalar in a nested structure."""
    out = [] if out is None else out
    if isinstance(value, dict):
        for key, item in value.items():
            out.append(str(key))
            _flatten(item, out)
    elif isinstance(value, list):
        for item in value:
            _flatten(item, out)
    else:
        out.append(str(value))
    return out


@pytest.fixture
def mock_env(monkeypatch):
    monkeypatch.setenv("PANTHEON_NEURON_MOCK", "1")
    yield
    monkeypatch.delenv("PANTHEON_NEURON_MOCK", raising=False)


def test_snapshot_contains_no_host_identifier_keys(mock_env):
    snapshot = pantheon_neuron.get_system_snapshot(neuron_device.discover())
    tokens = {token.lower() for token in _flatten(snapshot)}
    for key in FORBIDDEN_KEYS:
        assert key not in tokens, f"snapshot leaked '{key}'"


def test_snapshot_does_not_contain_this_machines_hostname(mock_env):
    """A key-name blocklist is not enough; check the actual value."""
    snapshot = pantheon_neuron.get_system_snapshot(neuron_device.discover())
    blob = json.dumps(snapshot).lower()

    hostname = socket.gethostname().lower()
    assert hostname
    assert hostname not in blob, "snapshot leaked the running host's name"

    fqdn = socket.getfqdn().lower()
    if fqdn and fqdn != "localhost":
        assert fqdn not in blob, "snapshot leaked the running host's FQDN"


def test_monitor_scrubs_instance_info_from_samples():
    """neuron-monitor emits instance_info; it must not survive ingest."""
    raw = {
        "instance_info": {
            "instance_id": "i-0123456789abcdef0",
            "instance_type": "trn1.32xlarge",
            "availability_zone": "us-east-1d",
        },
        "neuron_runtime_data": [
            {"report": {"execution_stats": {"total_executions": 5}}}
        ],
    }
    scrubbed = neuron_monitor._scrub(raw)

    assert "instance_info" not in scrubbed
    assert "i-0123456789abcdef0" not in json.dumps(scrubbed)
    # ...without discarding the metrics we actually came for.
    assert scrubbed["neuron_runtime_data"][0]["report"]["execution_stats"] == {
        "total_executions": 5
    }


def test_monitor_scrubs_nested_identifiers():
    raw = {"outer": {"inner": [{"hostname": "ip-10-0-0-1", "value": 3}]}}
    scrubbed = neuron_monitor._scrub(raw)
    assert "ip-10-0-0-1" not in json.dumps(scrubbed)
    assert scrubbed["outer"]["inner"][0]["value"] == 3


def test_aggregated_telemetry_is_clean(mock_env):
    """The mock loop deliberately injects instance_info to prove the path."""
    monitor = neuron_monitor.NeuronMonitor(period_seconds=0.01, mock=True)
    monitor.start([0, 1])
    import time

    time.sleep(0.1)
    metrics = monitor.stop()

    blob = json.dumps(metrics).lower()
    for key in FORBIDDEN_KEYS:
        assert key not in blob, f"aggregated telemetry leaked '{key}'"


@pytest.mark.parametrize(
    "path", sorted(glob.glob(os.path.join(REPO_ROOT, "database", "*.json")))
)
def test_committed_reports_are_clean(path):
    """Any report present in the tree must already be publishable."""
    with open(path, encoding="utf-8") as handle:
        report = json.load(handle)
    tokens = {token.lower() for token in _flatten(report)}
    for key in FORBIDDEN_KEYS:
        assert key not in tokens, f"{os.path.basename(path)} leaked '{key}'"
